name = "email-sender"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# KV 命名空间配置
# 使用以下命令创建：
# wrangler kv:namespace create "CONFIG_KV"
# wrangler kv:namespace create "CONFIG_KV" --preview
[[kv_namespaces]]
binding = "CONFIG_KV"
id = "请替换为您的KV命名空间ID"
preview_id = "请替换为您的预览KV命名空间ID"
