name = "email-sender"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[env.production]
vars = { ENVIRONMENT = "production" }

# KV 命名空间用于存储配置
[[kv_namespaces]]
binding = "CONFIG_KV"
id = "请在部署时使用 wrangler kv:namespace create CONFIG_KV 创建并替换此 ID"
preview_id = "请在部署时使用 wrangler kv:namespace create CONFIG_KV --preview 创建并替换此 ID"

# 环境变量说明
# 使用 wrangler secret put ADMIN_PASSWORD 设置管理员密码
# 默认密码为 admin123
